### PR TITLE
🗓 Remove locked timezone of the embedded calendar

### PR DESCRIPTION
**Pull request by rowanc1**
See #7

### CODE REVIEW

**Comment by choldgraf** [comment]
Hmm - this still seems to display in US/Pacific time:

image

**Comment by choldgraf** [comment]
@rowanc1 did you figure this one out?

**Comment by rowanc1** [comment]
I haven't looked into it at all since i made the PR! Feel free to close, I don't think it works..

**Comment by choldgraf** [comment]
Sounds good, let's close and figure out something better on the future.

**Pull request closed without merging**
